---
kind: pipeline
name: build_amd64

platform:
  os: linux
  arch: amd64

steps:
- name: iobroker_installer_download
  image: plugins/download
  settings:
    destination: .build/iobroker-stable.zip
    source: https://github.com/ioBroker/ioBroker/archive/stable-installer.zip

- name: iobroker_installer_checksum
  image: alpine
  commands:
  - "md5sum .build/iobroker-stable.zip > .build/iobroker-stable.md5sum"
  - rm .build/iobroker-stable.zip

- name: docker
  image: plugins/docker
  settings:
    build_args:
    - BASE=node:10-stretch
    - arch=amd64
    cache_from:
    - angelnu/iobroker:master-amd64
    - "angelnu/iobroker:${DRONE_BRANCH}-amd64"
    - "angelnu/iobroker:${DRONE_BRANCH}-amd64"
    password:
      from_secret: DOCKER_PASS
    repo: angelnu/iobroker
    tags:
    - "${DRONE_BRANCH}-${DRONE_COMMIT}-amd64"
    - "${DRONE_BRANCH}-amd64"
    - latest-amd64
    target: iobroker
    username:
      from_secret: DOCKER_USER

- name: full-docker
  image: plugins/docker
  settings:
    build_args:
    - BASE=node:10-stretch
    - arch=amd64
    cache_from:
    - angelnu/iobroker:full-master-amd64
    - "angelnu/iobroker:full-${DRONE_BRANCH}-amd64"
    - "angelnu/iobroker:${DRONE_BRANCH}-amd64"
    password:
      from_secret: DOCKER_PASS
    repo: angelnu/iobroker
    tags:
    - "full-${DRONE_BRANCH}-${DRONE_COMMIT}-amd64"
    - "full-${DRONE_BRANCH}-amd64"
    - full-latest-amd64
    target: full-iobroker
    username:
      from_secret: DOCKER_USER

---
kind: pipeline
name: build_arm

platform:
  os: linux
  arch: arm

steps:
- name: iobroker_installer_download
  image: plugins/download
  settings:
    destination: .build/iobroker-stable.zip
    source: https://github.com/ioBroker/ioBroker/archive/stable-installer.zip

- name: iobroker_installer_checksum
  image: alpine
  commands:
  - "md5sum .build/iobroker-stable.zip > .build/iobroker-stable.md5sum"
  - rm .build/iobroker-stable.zip

- name: docker
  image: plugins/docker
  settings:
    build_args:
    - BASE=node:10-stretch
    - arch=arm
    cache_from:
    - angelnu/iobroker:master-arm
    - "angelnu/iobroker:${DRONE_BRANCH}-arm"
    - "angelnu/iobroker:${DRONE_BRANCH}-arm"
    password:
      from_secret: DOCKER_PASS
    repo: angelnu/iobroker
    tags:
    - "${DRONE_BRANCH}-${DRONE_COMMIT}-arm"
    - "${DRONE_BRANCH}-arm"
    - latest-arm
    target: iobroker
    username:
      from_secret: DOCKER_USER

- name: full-docker
  image: plugins/docker
  settings:
    build_args:
    - BASE=node:10-stretch
    - arch=arm
    cache_from:
    - angelnu/iobroker:full-master-arm
    - "angelnu/iobroker:full-${DRONE_BRANCH}-arm"
    - "angelnu/iobroker:${DRONE_BRANCH}-arm"
    password:
      from_secret: DOCKER_PASS
    repo: angelnu/iobroker
    tags:
    - "full-${DRONE_BRANCH}-${DRONE_COMMIT}-arm"
    - "full-${DRONE_BRANCH}-arm"
    - full-latest-arm
    target: full-iobroker
    username:
      from_secret: DOCKER_USER

---
kind: pipeline
name: build_arm64

platform:
  os: linux
  arch: arm64

steps:
- name: iobroker_installer_download
  image: plugins/download
  settings:
    destination: .build/iobroker-stable.zip
    source: https://github.com/ioBroker/ioBroker/archive/stable-installer.zip

- name: iobroker_installer_checksum
  image: alpine
  commands:
  - "md5sum .build/iobroker-stable.zip > .build/iobroker-stable.md5sum"
  - rm .build/iobroker-stable.zip

- name: docker
  image: plugins/docker
  settings:
    build_args:
    - BASE=node:10-stretch
    - arch=arm64
    cache_from:
    - angelnu/iobroker:master-arm64
    - "angelnu/iobroker:${DRONE_BRANCH}-arm64"
    - "angelnu/iobroker:${DRONE_BRANCH}-arm64"
    password:
      from_secret: DOCKER_PASS
    repo: angelnu/iobroker
    tags:
    - "${DRONE_BRANCH}-${DRONE_COMMIT}-arm64"
    - "${DRONE_BRANCH}-arm64"
    - latest-arm64
    target: iobroker
    username:
      from_secret: DOCKER_USER

- name: full-docker
  image: plugins/docker
  settings:
    build_args:
    - BASE=node:10-stretch
    - arch=arm64
    cache_from:
    - angelnu/iobroker:full-master-arm64
    - "angelnu/iobroker:full-${DRONE_BRANCH}-arm64"
    - "angelnu/iobroker:${DRONE_BRANCH}-arm64"
    password:
      from_secret: DOCKER_PASS
    repo: angelnu/iobroker
    tags:
    - "full-${DRONE_BRANCH}-${DRONE_COMMIT}-arm64"
    - "full-${DRONE_BRANCH}-arm64"
    - full-latest-arm64
    target: full-iobroker
    username:
      from_secret: DOCKER_USER

---
kind: pipeline
name: build_manifest

platform:
  os: linux
  arch: amd64

steps:
- name: "manifest_${DRONE_BRANCH}-${DRONE_COMMIT}"
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: DOCKER_PASS
    platforms:
    - linux/amd64
    - linux/arm
    - linux/arm64
    target: "angelnu/iobroker:${DRONE_BRANCH}-${DRONE_COMMIT}"
    template: "angelnu/iobroker:${DRONE_BRANCH}-${DRONE_COMMIT}-ARCH"
    username:
      from_secret: DOCKER_USER

- name: "manifest_${DRONE_BRANCH}"
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: DOCKER_PASS
    platforms:
    - linux/amd64
    - linux/arm
    - linux/arm64
    target: "angelnu/iobroker:${DRONE_BRANCH}"
    template: "angelnu/iobroker:${DRONE_BRANCH}-${DRONE_COMMIT}-ARCH"
    username:
      from_secret: DOCKER_USER

- name: manifest_latest
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: DOCKER_PASS
    platforms:
    - linux/amd64
    - linux/arm
    - linux/arm64
    target: angelnu/iobroker:latest
    template: "angelnu/iobroker:${DRONE_BRANCH}-${DRONE_COMMIT}-ARCH"
    username:
      from_secret: DOCKER_USER

- name: "manifest_full-${DRONE_BRANCH}-${DRONE_COMMIT}"
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: DOCKER_PASS
    platforms:
    - linux/amd64
    - linux/arm
    - linux/arm64
    target: "angelnu/iobroker:full-${DRONE_BRANCH}-${DRONE_COMMIT}"
    template: "angelnu/iobroker:full-${DRONE_BRANCH}-${DRONE_COMMIT}-ARCH"
    username:
      from_secret: DOCKER_USER

- name: "manifest_full-${DRONE_BRANCH}"
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: DOCKER_PASS
    platforms:
    - linux/amd64
    - linux/arm
    - linux/arm64
    target: "angelnu/iobroker:full-${DRONE_BRANCH}"
    template: "angelnu/iobroker:full-${DRONE_BRANCH}-${DRONE_COMMIT}-ARCH"
    username:
      from_secret: DOCKER_USER

- name: manifest_full-latest
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: DOCKER_PASS
    platforms:
    - linux/amd64
    - linux/arm
    - linux/arm64
    target: angelnu/iobroker:full-latest
    template: "angelnu/iobroker:full-${DRONE_BRANCH}-${DRONE_COMMIT}-ARCH"
    username:
      from_secret: DOCKER_USER

depends_on:
- build_amd64
- build_arm
- build_arm64

...
