ARG BASE=node:8-slim
FROM $BASE

ARG arch=arm
ENV ARCH=$arch

# inspired by https://github.com/iobroker/docker-iobroker
MAINTAINER Vegetto <git@angelnu.com>

#Install adapters listed by adapters2install.json and add admin
ADD adapters2install.json adapters2install.json
RUN mv package.json package.json.org && \
    cp -a adapters2install.json package.json && \
    npm install --production --save --unsafe-perm --prefix /opt/iobroker

EXPOSE 8081 8082 8083 8084
ENTRYPOINT ["run.sh"]
CMD ["start"]
